language: c
dist: bionic
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler python3-pip
  - sudo pip3 install protobuf
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
env:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
script:
  - bash -ex .travis-opam.sh
